---
title: Isqiao.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
name: 乔闻
description: 随便写写，记录下日常。
url: https://isqiao.github.io
baseurl: 
github: isqiao
gitlab: 
gaaccount: 
comments: true
isso: 
disqus: 
permalink: "/:year/:month/:title"
paginate: 3
highlighter: rouge
markdown: kramdown
gems:
- jekyll-paginate
exclude:
- README.md
- LICENSE
plugins:
- jekyll-paginate
